const todo = require("../model/todo")


// create Todo
const createTodo = async (req, res)=>{
    const {title,body} = req.body
    try{
         const create_todo = await todo.create({title,body})
         res.status(201).json({create_todo})
        
    }catch (error){
        
        res.status(404).json({msg: "TODO not created"})
    }
}

const getAllTodos = async (req, res)=>{
    try{
        const todos = await todo.find()
        res.status(201).json({todos})
    }catch (error){
        res.status(404).json({msg: "TODO not found"})
    }

}
const singleTodo = async (req, res)=>{
    const {id} = req.params
    try{
        const toDo = await todo.findById(id)
        res.status(201).json(toDo)
    }catch (error){
        res.status(404).json({msg: "Single TODO not found"})
    }
}
const deleteTodo = async (req,res)=>{
    const {id} = req.params
    try{
        const deletedTodo = await todo.findByIdAndDelete(id)
        
        res.status(200).json({msg:'deleted'})
    }catch (error){
        res.status(404).json({msg: "cant delete this Todo"})
    }
}
const updateTodo = async (req, res)=>{
const {id} = req.params
try{
    const toDo = await todo.findById(id)
    const updatedTodo = await todo.findByIdAndUpdate(toDo, req.body, {new:true, runValidators:true})
    res.status(201).json({updatedTodo})
}catch (error){
     res.status(404).json({msg: "Not updated"})
    console.log(error);
}
}

const todedeleted = async (req, res)=>{
    const {id} = req.params
    try{
        const toDo = await todo.findByIdAndDelete(id)
        res.status(201).json({msg: 'deleted'})
    }catch (error){
       console.log(error);
    }
    
    // try {
    //     const todoDelete = await todo.findByIdAndDelete(id)
    //     res.status(200).json({msg: 'delete successful'})

        
    // } catch (error) {
    //     console.log(error);
        
    // }
}

module.exports = {createTodo, getAllTodos, singleTodo, updateTodo, deleteTodo, todedeleted}

